# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('UserPassword', models.CharField(max_length=30)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('Data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
